Repository FE14-Part3-Team3/The_julge, pull requests merged in 2025-05, with the labels that each got.

#59 ✨ [Feat] 내 프로필 카드 컴포넌트 api 연결 및 조건부 렌더링
  src/app/profile/worker/[id]/components/ProfileCard.tsx
  src/app/profile/worker/[id]/page.tsx
  src/components/Card/RegisterCard.tsx
  src/hooks/api/useUserService.ts
Labels: 🌱 Feat

#64 ✨ [Feat] 내 프로필의 편집기능과 등록하기 레이아웃을 구현하고 네트워크 요청을 보냅니다
  pnpm-lock.yaml
  public/assets/images/vector.svg
  src/app/layout.tsx
  src/app/profile/worker/[id]/register/page.tsx
  src/components/Input/SelectInput.tsx
  src/lib/react-query.ts
  src/types/api/user.ts
Labels: 🌱 Feat

#65 ✨ [Feat] 공고 등록 페이지 추가
  src/app/profile/worker/[id]/register/page.tsx
  src/app/shops/[shopId]/register-notice/components/NoticeRegisterForm.tsx
  src/app/shops/[shopId]/register-notice/page.tsx
  src/hooks/api/useNoticeService.ts
  src/types/api/notice.ts
Labels: 🌱 Feat

#66 ✨ [Feat] NoticeRegisterForm 활용, 수정이 가능하도록 페이지 구현
  src/app/shops/[shopId]/[noticeId]/edit/page.tsx
  src/app/shops/[shopId]/register-notice/components/NoticeRegisterForm.tsx
  src/hooks/api/useNoticeService.ts
Labels: 🔨 Refactor, 🌱 Feat

#67 ✨ [Feat] 로그인 및 회원가입 시 토큰을 로컬 스토리지에 저장하는 기능 추가
  src/app/login/page.tsx
  src/app/signup/page.tsx
Labels: 🌱 Feat

#70 ✨ [Feat] 테이블 컴포넌트화 및 API 연결 , 프로필 상세 페이지 완성
  src/app/profile/worker/[id]/components/ApplicationTable.tsx
  src/app/profile/worker/[id]/components/ProfileCard.tsx
  src/app/profile/worker/[id]/page.tsx
  src/app/profile/worker/[id]/register/page.tsx
  src/components/Input/SelectInput.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Table/StatusButton.tsx
  src/components/Table/Table.tsx
  src/components/Table/TableSchemas.tsx
  src/hooks/api/useUserService.ts
  src/types/api/notice.ts
Labels: 🌱 Feat

#74 ✨ [Feat, Refactor] GNB를 구현, 인증 정보를 관리하는 AuthContext 작성, 리다이렉트 기능 추가
  public/assets/icons/notification.svg
  public/assets/icons/search.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/components/MemberTypeRadioInput.tsx
  src/app/(auth)/signup/components/RadioButton.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/layout.tsx
  src/app/layout.tsx
  src/app/shops/layout.tsx
  src/components/GNB/GlobalHeader.tsx
  src/components/GNB/Notification.tsx
  src/components/GNB/NotificationPanel.tsx
  src/components/GNB/SearchBar.tsx
  src/contexts/AuthContext.tsx
Labels: 🐞Fix, 🔨 Refactor, 🌱 Feat

#71 ✨ [Feat] 공고 리스트 (로그인 상태 / 비로그인상태)
  next.config.ts
  package-lock.json
  public/assets/images/arrow_up.svg
  public/assets/images/arrow_up_gray.svg
  public/assets/images/arrow_up_red_30.svg
  public/assets/images/arrow_up_red_40.svg
  public/assets/images/blur-placeholder.jpg
  public/assets/images/clock.svg
  public/assets/images/clock_gray.svg
  public/assets/images/close.svg
  public/assets/images/delete_red.svg
  public/assets/images/map_gray.svg
  public/assets/images/placeholder.png
  public/assets/images/select_arrow.svg
  src/app/notices/[noticeId]/page.tsx
  src/app/notices/components/PaginatedNoticeList.tsx
  src/app/notices/components/RecommendedNotices.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/Card/EmptyCard.tsx
  src/components/FallbackImage/FallbackImage.tsx
  src/components/FilterPanel/FilterPanel.tsx
  src/components/IconText/IconText.tsx
  src/components/Input/NoticeSelectInput.tsx
  src/components/Notice/NoticeCard.tsx
  src/components/Notice/NoticeCardView.tsx
  src/components/Notice/PayBadge.tsx
  src/hooks/api/useAlertService.ts
  src/hooks/api/useApplications.ts
  src/hooks/api/useNoticeService.ts
  src/hooks/api/useNoticeService.tsx
  src/hooks/api/useParsedNoticeQuery.tsx
  src/hooks/api/useShopService.ts
  src/hooks/api/useUserService.ts
  src/hooks/usePagination.ts
  src/lib/getQueryString.ts
  src/lib/imageAssets.ts
  src/types/api/notice.ts
  src/types/common.ts
Labels: 🌱 Feat

#78 🐛 [Fix/Refactor] 검색창을 수정해 PaginatedNoticeList 컴포넌트와 연결
  src/components/GNB/GlobalHeader.tsx
  src/components/GNB/Notification.tsx
  src/components/GNB/SearchBar.tsx
Labels: 🐞Fix

#80 🐛 [Fix/Refactor] dummy data 삭제 및 가게등록하기 버튼 클릭 시 가게등록폼으로 연결
  src/app/(main)/shops/[shopId]/page.tsx
  src/app/(main)/shops/new/page.tsx
  src/app/(main)/shops/page.tsx
  src/components/ShopNotices/ShopNotices.tsx
  src/components/ShopNotices/dummyData.ts
  src/lib/shopApi.ts
Labels: 🔨 Refactor, 🌱 Feat

#83 Fix/gnb
  src/app/(main)/notices/components/PaginatedNoticeList.tsx
  src/app/(main)/page.tsx
  src/app/(main)/profile/worker/[id]/register/page.tsx
  src/app/(main)/shops/[shopId]/layout.tsx
  src/app/(main)/shops/[shopId]/page.tsx.bak2
  src/app/(main)/shops/[shopId]/register-notice/components/NoticeRegisterForm.tsx
  src/app/(main)/shops/[shopId]/register/components/ImageUploader.tsx
  src/app/(main)/shops/[shopId]/register/components/ShopRegisterForm.tsx
  src/app/(main)/shops/[shopId]/register/page.tsx
  src/components/GNB/GlobalHeader.tsx
  src/components/GNB/SearchBar.tsx
  src/hooks/api/useAlertService.ts
Labels: 🐞Fix, 🌱 Feat

#86 🐛 [Fix] 가게상세정보페이지와 공고등록페이지 연결
  src/app/(main)/shops/[shopId]/page.tsx
  src/components/ShopCard/ShopAction.tsx
Labels: 🐞Fix, 🌱 Feat

#87 🐛 [Fix] 신청 내역 중복 출력 수정 및 테이블 페이지네이션 수정
  src/app/(main)/shops/[shopId]/edit/components/ShopEditForm.tsx
  src/app/(main)/shops/[shopId]/page.tsx
  src/app/(main)/shops/[shopId]/register/hooks/useShopRegister.ts
  src/components/Modal/AlertModal.tsx
  src/components/ShopCard/ShopAction.tsx
  src/components/ShopNotices/ShopNotices.tsx
Labels: 🐞Fix, 🌱 Feat
