Repository FE14-Part3-Team3/The_julge, pull requests merged in 2025-04, with the labels that each got.

#8 Feature/components/button
  src/components/Button/Button.tsx
Labels: 🌱 Feat

#11 전역 스타일링 설정
  public/fonts/SpoqaHanSansNeo-Bold.ttf
  public/fonts/SpoqaHanSansNeo-Bold.woff
  public/fonts/SpoqaHanSansNeo-Bold.woff2
  public/fonts/SpoqaHanSansNeo-Regular.ttf
  public/fonts/SpoqaHanSansNeo-Regular.woff
  public/fonts/SpoqaHanSansNeo-Regular.woff2
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.js
Labels: 🌱 Feat

#29 Tailwindcss 커스텀 스타일 적용
  package.json
  pnpm-lock.yaml
  postcss.config.js
  postcss.config.mjs
  src/app/globals.css
  tailwind.config.js
Labels: 🐞Fix

#28 공통 컴포넌트 모달 구현
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  public/assets/images/check.svg
  public/assets/images/notification.svg
  src/components/Button/ModalButton.tsx
  src/components/Modal/AlertModal.tsx
  src/components/Modal/ApplyModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/RegisterModal.tsx
Labels: 🌱 Feat

#30 fix: 버튼 컴포넌트의 variant 타입 solid -> primary 변경 클래스 스타일 전역변수로 수정
  src/components/Button/Button.tsx
Labels: 🐞Fix, 💄 Style

#33 fix: clsx 의존성 추가
  package.json
Labels: 🐞Fix

#37 fix: 전역 tailwind 스타일 적용
  src/components/Button/ModalButton.tsx
  src/components/Modal/AlertModal.tsx
  src/components/Modal/ApplyModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/RegisterModal.tsx
Labels: 🌱 Feat

#31 Feature/component/input
  src/components/Input/Input.tsx
  src/components/Input/InputField.tsx
  src/components/Input/SelectInput.tsx
Labels: 🌱 Feat

#36 Feature/store register #10
  src/app/employer/layout.tsx
  src/app/employer/page.tsx
  src/app/layout.tsx
  src/components/Card/RegisterCard.tsx
Labels: 🌱 Feat

#41 ✨ [Feat] 로그인/회원가입 페이지 구현하고 공용 Input컴포넌트를 수정, 회원가입에서 사용되는 라디오 버튼 컴포넌트를 구현했습니다.
  package.json
  pnpm-lock.yaml
  public/assets/images/ellipse.svg
  public/assets/images/logo.svg
  src/app/login/page.tsx
  src/app/signup/components/MemberTypeRadioInput.tsx
  src/app/signup/components/RadioButton.tsx
  src/app/signup/page.tsx
  src/components/Button/Button.tsx
  src/components/Input/Input.tsx
  src/components/Modal/AlertModal.tsx
  src/components/Modal/ApplyModal.tsx
  src/components/Modal/RegisterModal.tsx
Labels: 🌱 Feat

#45 ✨[Feat] customHook APl - React Query 기반으로 요청/응답 관리
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  postcss.config.cjs
  src/app/employer/layout.tsx
  src/app/employer/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/hooks/api/useAlertService.ts
  src/hooks/api/useApplications.ts
  src/hooks/api/useAuthentication.ts
  src/hooks/api/useImageUpload.ts
  src/hooks/api/useNoticeService.ts
  src/hooks/api/useShopService.ts
  src/hooks/usePagination.ts
  src/lib/axios.ts
  src/lib/dummy
  src/types/api/application.ts
  src/types/api/notice.ts
  src/types/api/notification.ts
  src/types/api/shop.ts
  src/types/api/user.ts
  src/types/common.ts
Labels: 📂 Docs, 🌱 Feat

#47 ✨ [Feat] 페이지네이션 기능
  package.json
  pnpm-lock.yaml
  public/assets/icons/chevron/chevron-outline.svg
  public/assets/icons/chevron/chevron.svg
  src/app/page.tsx
  src/app/providers.tsx
  src/components/Modal/RegisterModal.tsx
  src/components/Pagination/ChevronButton.tsx
  src/components/Pagination/PageButton.tsx
  src/components/Pagination/Pagination.tsx
  src/components/dummy
  src/hooks/dummy
  src/hooks/usePagination.ts
  src/types/dummy
Labels: 🌱 Feat

#51 ✨ [Feat] 가게 등록 상태 여부에 따라 화면 분기 처리
  public/temp-restaurant.jpg
  src/app/shops/[shopId]/layout.tsx
  src/app/shops/[shopId]/page.tsx
  src/app/shops/layout.tsx
  src/app/shops/page.tsx
  src/components/Card/ShopOverview.tsx
  src/components/Notice/NoticeEmptyCard.tsx
  src/components/Notice/NoticeList.tsx
  src/components/Shop/ShopInfo.tsx
  src/lib/shared/api.ts
  src/lib/shopApi.ts
  src/mock/noticeData.ts
  src/types/ShopTypes.ts
Labels: 🌱 Feat

#54 ✨ [Feat] 가게 등록하기 폼 구현
  public/assets/images/camera.svg
  src/app/login/page.tsx
  src/app/shops/[shopId]/register/components/ImageUploader.tsx
  src/app/shops/[shopId]/register/components/ShopRegisterForm.tsx
  src/app/shops/[shopId]/register/page.tsx
  src/components/Input/SelectInput.tsx
  src/lib/constants/addressOptions.ts
  src/lib/constants/foodCategory.ts
Labels: 🌱 Feat
